MVC/Natural Feelings Admi/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Natural_Feelings_Admi.API;
using Natural_Feelings_Admi.Models;

namespace Natural_Feelings_Admi.Controllers
{
    public class AdminController : Controller
    {

        public List<SeasonModel> GetSeason()
        {
            Admin admin = new Admin();
            return admin.GetSeason().GetAwaiter().GetResult();
        }

        public List<OfferModel> GetOffer()
        {
            Admin admin = new Admin();
            return admin.GetOffer().GetAwaiter().GetResult();
        }

        public OfferModel GetOfferId(int codigo)
        {
            Admin admin = new Admin();
            return admin.BuscarOferta(codigo).GetAwaiter().GetResult();
        }

        public IActionResult DeleteSeason(SeasonModel season)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Admin admin=new Admin();
            ViewBag.result=admin.DeteleSeason(season).Result;
            Console.WriteLine(ViewBag.result);
            ViewBag.Season = this.GetSeason();
            return View("AdminTemporadas");
        }

        public IActionResult DeleteOffer(OfferModel offer)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Admin admin = new Admin();
            ViewBag.result = admin.DeteleOffer(offer).Result;
            ViewBag.Offer = this.GetOffer();
            return View("AdminOfertas");
        }

        public IActionResult CreateOffer(OfferModel offer)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Admin admin = new Admin();
            ViewBag.resultcrear = admin.CreateOffer(offer).Result;
            ViewBag.Offer = this.GetOffer(); 
            return View("AdminOfertas");
        }

        public IActionResult EditOffer(OfferModel offer)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Admin admin = new Admin();
            ViewBag.resultedit = admin.EditOffer(offer).Result;
            ViewBag.Offer = this.GetOffer();
            return View("AdminOfertas");
        }

        public IActionResult EditSeason(SeasonModel season)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Admin admin = new Admin();
            ViewBag.resultedit2 = admin.EditSeason(season).Result;
            ViewBag.Season = this.GetSeason();
            return View("AdminTemporadas");
        }

        public IActionResult CreateSeason(SeasonModel season)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Admin admin = new Admin();
            ViewBag.result3 = admin.CreateSeason(season).Result;
            ViewBag.Season = this.GetSeason();
            return View("AdminTemporadas");
        }

        public SeasonModel GetSeasonId(int codigo)
        {
            Admin admin = new Admin();
            return admin.BuscarSeason(codigo).GetAwaiter().GetResult();
        }

        public IActionResult AdminTemporadas()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            ViewBag.Season=this.GetSeason();
            return View();
        }

        public IActionResult AdminOfertas()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            ViewBag.Offer = this.GetOffer();
            return View();
        }
    }
}

MVC/Natural Feelings Admi/Controllers/HotelController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Natural_Feelings_Admi.Models;
using Natural_Feelings_Admi.API;
using System.Text;
using Natural_Feelings_Hotel_API.Models;
using System.Data;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Org.BouncyCastle.Asn1.X509;

namespace Natural_Feelings_Admi.Controllers
{
    public class HotelController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;

        public HotelController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }

        public ActionResult TodayStatus()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }

        public ActionResult AvailabilityRoomView()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            return View("AvailabilityRoom");
        }
        public string AvailabilityRoom(ReservationModel imput)
        {
            Hotel hotelAPI = new Hotel();
            List<ReservationModel> availabilityRoomModels = hotelAPI.GetAvailabilityRoom(imput).GetAwaiter().GetResult();
            //Console.WriteLine("_______________" + imput.Habitation.IdHabitation);
            string cadena = "";
            foreach (var item in availabilityRoomModels)
            {
                cadena += "<tr>" +
                            "<td scope = 'row'>" + item.Habitation.IdHabitation + "</td>" +
                             "<td>" + item.Habitation.Rate.Name + "</td>" +
                             "<td>" + item.Habitation.Rate.Price + "</td>" +
                         "</tr>";
            }
            Console.WriteLine(availabilityRoomModels);
            return cadena;
        }

        public async Task<ActionResult> PDFReporte()
        {
            try
            {
                Document doc = new Document();
                string nombreDocumento = "Reporte" + DateTime.Now.ToString("dd-MMMM-yy") + ".pdf";
                FileStream file = new FileStream(nombreDocumento, FileMode.OpenOrCreate);
                PdfWriter writer = PdfWriter.GetInstance(doc, file);
                doc.AddTitle("Reporte" + DateTime.Now.ToString("dd - MMMM - yy"));
                doc.Open();

                Hotel jefaturaData = new Hotel();

                List<TodayStatusModel> reportes = await jefaturaData.reporte();
                PdfPTable table = new PdfPTable(3);

                Font fontTitle = FontFactory.GetFont(FontFactory.COURIER_BOLD, 14);
                Font font9 = FontFactory.GetFont(FontFactory.TIMES, 12);

                doc.Add(new Paragraph(20, "Reporte de Habitaciones " + DateTime.Now, fontTitle));
                doc.Add(new Chunk("\n"));

                float[] widths = new float[3];
                for (int i = 0; i < 3; i++)
                    widths[i] = 4f;

                table.SetWidths(widths);
                table.WidthPercentage = 100;

                PdfPCell cell = new PdfPCell(new Phrase("columns"));
                cell.Colspan = 3;

                table.AddCell(new Phrase("Numero"));
                table.AddCell(new Phrase("Tipo"));
                table.AddCell(new Phrase("Estado"));

                var status="";
                foreach (TodayStatusModel reporte in reportes)
                {
                    if(String.Compare(reporte.Status, "TRUE") != 0)
                        {
                        status = "Disponible";
                    }
                        else
                    {
                        status = "Ocupado";
                    }
                    table.AddCell(new Phrase(reporte.ID_Habitation + "", font9));
                    table.AddCell(new Phrase(reporte.ID_Rate + "", font9));
                    table.AddCell(new Phrase(status + "", font9));
                }
                doc.Add(table);
                writer.Close();
                doc.Close();
                file.Dispose();
                var pdf = new FileStream(nombreDocumento, FileMode.Open, FileAccess.Read);
                
                return File(pdf, "application/pdf");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult ModifyPages()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }
        public async Task<ActionResult> AboutUS()
        {

            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }
        public bool UpdateAboutUs(HotelModel imput)
        {
            HotelModel hotelModel = new HotelModel {
                IdHotel = 0,
                Description = "",
                AboutUS = imput.AboutUS,
                Adress = ""
            };
            Hotel hotelAPI = new Hotel();
            bool response = hotelAPI.UpdateAboutUs(hotelModel).Result;
            if (response)
                return true;
            else
                return false;
        }
        public async Task<ActionResult> HomeModify()
        {

            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }
        public ActionResult UpdateHome(HotelModel hotelModel)
        {
            hotelModel.IdHotel = 0;
            hotelModel.AboutUS = "";
            hotelModel.Adress = "";
            Hotel hotelAPI = new Hotel();
            bool response = hotelAPI.UpdateHome(hotelModel).Result;
            //Console.WriteLine(hotelModel.Description+"///"+hotelModel.Image.ImageForm);
            //bool response = false;
            return RedirectToAction("UpdateHome");
        }

        public IActionResult Facilities()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Facility facility = new Facility();
            ViewBag.facilities = facility.GetFacilities().GetAwaiter().GetResult();
            return View();
        }

        public IActionResult CreateFacility(FacilityModel facilityModel)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Facility facility = new Facility();
            ViewBag.facilities = facility.CreateFacility(facilityModel).GetAwaiter().GetResult();
            ViewBag.facilities = facility.GetFacilities().GetAwaiter().GetResult();
            return View("Facilities");
        }

        public IActionResult UpdateFacility(FacilityModel facilityModel)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Facility facility = new Facility();
            ViewBag.facilities = facility.UpdateFacility(facilityModel).GetAwaiter().GetResult();
            ViewBag.facilities = facility.GetFacilities().GetAwaiter().GetResult();
            return View("Facilities");
        }

        public IActionResult DeleteFacility(FacilityModel facilityModel)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Facility facility = new Facility();
            ViewBag.facilities = facility.DeleteFacility(facilityModel).GetAwaiter().GetResult();
            ViewBag.facilities = facility.GetFacilities().GetAwaiter().GetResult();
            return View("Facilities");
        }

        public IActionResult ReservationList()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Room room = new Room();
            ViewBag.reservations = room.GetReservations().GetAwaiter().GetResult();
            return View();
        }
        public async Task<ActionResult> Adress()
        {

            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }

        public bool UpdateAdress(HotelModel imput)
        {
            HotelModel hotelModel = new HotelModel
            {
                IdHotel = 0,
                Description = "",
                AboutUS = "",
                Adress = imput.Adress
            };
            Hotel hotelAPI = new Hotel();
            bool response = hotelAPI.UpdateAdress(hotelModel).Result;
            if (response)
                return true;
            else
                return false;
        }
    }
}

MVC/Natural Feelings Admi/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Natural_Feelings_Admi.API;
using Natural_Feelings_Admi.Models;

namespace Natural_Feelings_Admi.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> loginUser(AdmiModel admiModel)
        {
            Console.WriteLine("boton iniciar sesion");
            Admin temp = new Admin();
            AdmiModel aux = (AdmiModel) await temp.getAdmi(admiModel);
            if(aux != null)
            {
                if (aux.Name == admiModel.Name && aux.Authenticated)
                {
                    HttpContext.Session.SetString("User", aux.Name);

                    ViewBag.userName = HttpContext.Session.GetString("User");

                    return View("inicio");
                }
                else
                {
                    ViewBag.validation = false;
                    return View("Index");
                }
            }
            else
            {
                ViewBag.validation = false;
                return View("Index");
            }
        }

        public async Task<IActionResult> logout()
        {
            Console.WriteLine("boton cerrar sesion");

            HttpContext.Session.Remove("User");

            return View("Index");
        }

        public IActionResult Inicio()
        {

            ViewBag.userName = HttpContext.Session.GetString("User");
            return View("Inicio");
        }
    }
}

MVC/Natural Feelings Admi/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using Natural_Feelings_Admi.API;
using Natural_Feelings_Admi.Models;
using Newtonsoft.Json;

namespace Natural_Feelings_Admi.Controllers
{
    public class RoomController : Controller
    {
        public IActionResult Manage()
        {
            Room room = new Room();
            ViewBag.Rates = room.GetRates().GetAwaiter().GetResult();
            ViewBag.Rooms = room.GetRooms().GetAwaiter().GetResult();
            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }

        public List<RateModel> GetRate()
        {
            Room room = new Room();
            return room.GetRates().GetAwaiter().GetResult();
        }

        public ActionResult Rate()
        {
            ViewBag.Rate = this.GetRate();
            return View("Rate");
        }


        public bool UpdateRoomState(RoomModel roomModel)
        {
            Room room = new Room();
            return room.UpdateRoomState(roomModel).GetAwaiter().GetResult();
        }

       

        public RateModel GetRateById(RateModel rateModel)
        {
            Room room = new Room();
            return room.GetRateById(rateModel).GetAwaiter().GetResult();
        }
        /*
        public bool UpdateRate()
        {
            Console.WriteLine(JsonConvert.SerializeObject(rateModel));
            Room room = new Room();
            return room.UpdateRate(rateModel).GetAwaiter().GetResult();
        }
        */

        public RoomModel GetRoomById(RoomModel roomModel)
        {
            
            Room roomAPI = new Room();
            return roomAPI.GetRoomById(roomModel).GetAwaiter().GetResult();
        }

        public IActionResult UpdateRoom(RoomModel roomModel)
        {
            Console.WriteLine(JsonConvert.SerializeObject(roomModel));
            Room room = new Room();
            ViewBag.Rates = room.GetRates().GetAwaiter().GetResult();
            ViewBag.Rooms = room.GetRooms().GetAwaiter().GetResult();
            ViewBag.Response = room.UpdateRoom(roomModel).GetAwaiter().GetResult();
            return View("Manage");
        }

        public IActionResult UpdateRate(RateModel rateModel)
        {
            //Console.WriteLine(JsonConvert.SerializeObject(rateModel));
            Room room = new Room();
            ViewBag.Rates = room.GetRates().GetAwaiter().GetResult();
            ViewBag.Rooms = room.GetRooms().GetAwaiter().GetResult();
            ViewBag.Response = room.UpdateRate(rateModel).GetAwaiter().GetResult();
            return View("Manage");
        }
    }
}

MVC/Natural Feelings Admi/Views/Shared/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@using Microsoft.AspNetCore.Http
@using Natural_Feelings_Admi.API
@model Natural_Feelings_Admi.Models.AdmiModel
@{
	Hotel homeAPI = new Hotel();
	HotelModel homeModel = homeAPI.ReadHome().GetAwaiter().GetResult();

}
<div class="inner">
	<div>
		<header id="header">
			<a asp-action="HomeView" asp-controller="Home" class="logo"> <img src="~/img/Logo Natural Feelings.png" width="100" height="100"> <strong>Hotel</strong> - Natural Feelings</a>
		</header>
	</div>

	<div class="text-center">
        <h2 class="display-4">Inicio de Sesion</h2>
    </div>

    <div class="text-center">
        @if (ViewBag.validation != null)
        {
            @if (!ViewBag.validation)
            {
                <div class="alert alert-danger" role="alert">
                    Su usuario y contraseña son incorrectas o no se encuentra autentificado 
                </div>
            }
        }
    </div>

    <form asp-controller="Login" asp-action="loginUser" method="post">
	    <div class="mt-5">
		    <div class="col-md-12 text-center">
                <label for="admiuser" class="form-label text">Usuario</label>
                <input asp-for="Name" type="text" class="form-control text-center" required id="Name" name="Name" placeholder="Nombre del usuario">
            </div>
            <div class="col-md-12 mt-3 text-center">
                <label for="pass" class="form-label">Contraseña</label>
                <input asp-for="Password" type="password" class="form-control text-center" required id="Password" name="Password" placeholder="Contraseña del usuario">
            </div>
            <div class="col-12 w-auto mx-3 text-center my-3">
                <button type="submit" class="btn btn-primary text-center mt-3">Iniciar Sesion</button>
            </div>
	    </div>
    </form>
</div>

MVC/Natural Feelings Admi/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
    Editorial by HTML5 UP
    html5up.net |
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
@using Microsoft.AspNetCore.Http
@using Natural_Feelings_Admi.API
<head>
    <title>Natural Feelings</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/js/Funciones.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
        function changeImage1(){
            $('#probando').html('<img src="/galery/paseo.jpg" style="width:100%">');
        }
        function changeImage2(){
            $('#probando').html('<img src="/galery/paseo2.jpg" style="width:100%">');
        }
        function changeImage3(){
            $('#probando').html('<img src="/galery/rio.jpg" style="width:100%">');
        }
        function changeImage4(){
            $('#probando').html('<img src="/galery/bungee.jpg" style="width:100%">');
        }
        function changeImage5(){
            $('#probando').html('<img src="/galery/bungee2.jpg" style="width:100%">');
        }
        function changeImage6(){
            $('#probando').html('<img src="/galery/rafting.jpg" style="width:100%">');
        }
        function changeImage7(){
            $('#probando').html('<img src="/galery/termal.jpg" style="width:100%">');
        }
        function changeImage8(){
            $('#probando').html('<img src="/galery/termal2.jpg" style="width:100%">');
        }
    </script>
    <script type="text/javascript" language="javascript">
        function noBack() {
            window.history.forward()
        }
        noBack();
        window.onload = noBack;
        window.onpageshow = function (evt) { if (evt.persisted) noBack(); }
        window.onunload = function () { void (0); }
    </script>
</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main">
            <div class="inner">
                <header id="header">
                    <div class="row row-cols-lg-2 row-cols-sm-1">
                        <div class="col-lg-9 col-sm-12">
                            <a asp-action="HomeView" asp-controller="Home" class="logo"> <img src="~/img/Logo Natural Feelings.png" style="width: 4em;"> <strong>Hotel</strong> - Natural Feelings</a>
                        </div>
                        <div class="col-lg-3 col-sm-12">
                            <p class="mt-lg-3 mt-5">Bienvenido @ViewBag.userName</p>
                            <a asp-action="logout" asp-controller="Login"><b class="mt-4 mt-lg-3">Cerrar sesión</b></a>
                        </div>
                    </div>
                </header>
            </div>
            @RenderBody()

        </div>
        <!-- Sidebar -->
        <div id="sidebar">
            <div class="inner">
                <!-- Menu -->
                <nav id="menu">
                    <header class="major">
                        <h2>Menu</h2>
                    </header>
                    <ul>
                        <li><a asp-controller="Home" asp-action="HomeView">Inicio</a></li>
                        <li><a asp-controller="Hotel" asp-action="ModifyPages">Modificar Paginas</a></li>
                        <li><a asp-controller="Hotel" asp-action="ReservationList">Listado de reservaciones</a></li>
                        <li><a asp-controller="Hotel" asp-action="TodayStatus">Ver estado del hotel</a></li>
                        <li><a asp-controller="Admin" asp-action="AdminTemporadas">Administrar Temporadas</a></li>
                        <li><a asp-controller="Admin" asp-action="AdminOfertas">Administrar Ofertas</a></li>
                        <li><a asp-controller="Room" asp-action="Manage">Administrar Habitaciones</a></li>
                        <li><a asp-controller="Hotel" asp-action="AvailabilityRoomView">Consultar disponibilidad</a></li>
                        <li><a asp-controller="Publicity" asp-action="AddAdvertising">Publicidad</a></li>
                    </ul>
                </nav>

                <!-- Footer -->
                <footer id="footer"
                    <p class="copyright">&copy; (2022) Hotel Natural Feelings.</p>
                </footer>

            </div>
        </div>

    </div>

    <!-- Scripts -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/browser.min.js"></script>
    <script src="~/js/breakpoints.min.js"></script>
    <script src="~/js/util.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC/Natural Feelings Admi/Views/Shared/_Layout2.cshtml
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net |
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
@using Microsoft.AspNetCore.Http
@using Natural_Feelings_Admi.API
<head>
    <title>Natural Feelings</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/js/Funciones.js"></script>
    <script type="text/javascript">
        function changeImage1(){
            $('#probando').html('<img src="/galery/paseo.jpg" style="width:100%">');
        }
        function changeImage2(){
            $('#probando').html('<img src="/galery/paseo2.jpg" style="width:100%">');
        }
        function changeImage3(){
            $('#probando').html('<img src="/galery/rio.jpg" style="width:100%">');
        }
        function changeImage4(){
            $('#probando').html('<img src="/galery/bungee.jpg" style="width:100%">');
        }
        function changeImage5(){
            $('#probando').html('<img src="/galery/bungee2.jpg" style="width:100%">');
        }
        function changeImage6(){
            $('#probando').html('<img src="/galery/rafting.jpg" style="width:100%">');
        }
        function changeImage7(){
            $('#probando').html('<img src="/galery/termal.jpg" style="width:100%">');
        }
        function changeImage8(){
            $('#probando').html('<img src="/galery/termal2.jpg" style="width:100%">');
        }
    </script>
    <script type="text/javascript" language="javascript">
        function noBack() {
            window.history.forward()
        }
        noBack();
        window.onload = noBack;
        window.onpageshow = function (evt) { if (evt.persisted) noBack(); }
        window.onunload = function () { void (0); }
    </script>
</head>
<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
		<div id="main">
			@RenderBody()

		</div>

	</div>

	<!-- Scripts -->
	<script src="~/js/jquery.min.js"></script>
	<script src="~/js/browser.min.js"></script>
	<script src="~/js/breakpoints.min.js"></script>
	<script src="~/js/util.js"></script>
	<script src="~/js/main.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

MVC/Natural Feelings Admi/Views/Shared/inicio.cshtml
@{
	ViewData["Title"] = "Home Page";
}
@using Microsoft.AspNetCore.Http
@using Natural_Feelings_Admi.API
@model Natural_Feelings_Admi.Models.AdmiModel
@{
	Hotel homeAPI = new Hotel();
	HotelModel homeModel = homeAPI.ReadHome().GetAwaiter().GetResult();
}
<div class="inner">

	<div class="text-center">
        <p class="display-4 align-content-center">Parte Administrativa</p>
		<p class="display-4 align-content-center">Hotel Natural Feelings</p>
    </div>

</div>