MVC/Natural Feelings Admi/Controllers/PublicityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Natural_Feelings_Admi.API;
using Natural_Feelings_Admi.Models;
using Natural_Feelings_Hotel.Models;
using System.IO;

namespace Natural_Feelings_Hotel.Controllers
{
    public class PublicityController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;

        public PublicityController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }

        public ActionResult AddAdvertising()
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            return View();
        }

        [HttpPost]
        public ActionResult Create(AdvertisingModel advertising)
        {
            ViewBag.userName = HttpContext.Session.GetString("User");
            Advertising advertisingAPI = new Advertising();
            if(!advertising.Link.Contains("https://"))
            {
                advertising.Link = "https://" + advertising.Link;
            }
            ViewBag.Response = advertisingAPI.create(advertising).GetAwaiter().GetResult();
            return View("AddAdvertising");
        }
    }
}

MVC/Natural Feelings Admi/Views/Publicity/AddAdvertising.cshtml
@*
*@
@model Natural_Feelings_Hotel.Models.AdvertisingModel
@{

}
<div class="inner">

    <div class="text-center">
        <h2 class="display-4">Publicidad</h2>
        @if (ViewBag.Response != null)
        {
            @if (ViewBag.Response == true)
            {
                <div class="alert alert-primary" role="alert">
                    Creado con éxito
                </div>
            }
            else
            {
                <div class="alert alert-danger" role="alert">
                    Ocurrió un error
                </div>
            }
        }
    </div>

    <div class="text-center my-5">
        <form asp-action="create" asp-controller="Publicity" method="post" enctype="multipart/form-data" runat="server">
            <div class="row row-cols-sm-1 row-cols-lg-2">

                <div class="col-lg-6 col-sm-12">
                    <label for="image" class="row m-auto justify-content-center">Imagen actual</label>
                    <img id="image" class="row m-auto" src="/assets/select.svg" style="border-style: dotted; width: 100%" />
                </div>

                <div class="col-lg-6 col-sm-12">
                    <div class="row">
                        <label for="link" class="col-lg-12">Link destino: </label>
                        <input id="link" class="col-lg-12" type="text" asp-for="@Model.Link" required />
                    </div><br>

                    <div class="row">
                        <label class="col-lg-12">Subir imagen: </label>
                        <div class="custom-file">
                            <input type="file" runat="server" class="p-0 custom-file-input col-lg-12" id="imageName" asp-for="@Model.Image.ImageForm" required>
                            <label class="custom-file-label form-control-lg col-lg-12" for="imageName">Choose file</label>
                        </div>
                    </div>

                    <div class="row justify-content-end my-5 ">
                        <button type="submit" class="btn btn-primary col-lg-3 mx-1 my-1">Aceptar</button>
                        <button type="reset" class="btn btn-secondary col-lg-3 mx-1 my-1">Cancelar</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

<script language="JavaScript">
    function readURL(input) {
    if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imageName").change(function () {
        readURL(this);
    });
</script>

<script>
    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>