MVC/Natural Feelings Hotel/Natural Feelings Hotel/Controllers/HabitationController.cs
using EASendMail;
using Microsoft.AspNetCore.Mvc;
using Natural_Feelings_Hotel.API;
using Natural_Feelings_Hotel.Models;
using Newtonsoft.Json;

namespace Natural_Feelings_Hotel.Controllers
{
    public class HabitationController : Controller
    {

        private readonly IWebHostEnvironment webHostEnvironment;

        public HabitationController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }
        public IActionResult Facilities()
        {
            return View();
        }

        public ActionResult Rate()
        {
            return View();
        }

        public ActionResult Reservation()
        {
            Habitation habitation = new Habitation();
            ViewBag.Rates = habitation.ReadRate().GetAwaiter().GetResult();
            return View();
        }

        public HabitationModel ValidateDateRange(ReservationModel reservationModel)
        {

            //Console.WriteLine(reservationModel.StartDate);
            //Console.WriteLine(reservationModel.EndDate);
            Habitation habitation = new Habitation();
            HabitationModel prueba = habitation.ValidateDateRange(reservationModel).GetAwaiter().GetResult();
            return prueba;
        }

        public ActionResult ReserveHabitation(ReservationModel reservationModel)
        {
            //Console.WriteLine(reservationModel.StartDate);
            //Console.WriteLine(reservationModel.EndDate);
            Habitation habitation = new Habitation();
            reservationModel.Habitation.Image = new ImageModel
            {
                IdImage = "",
                ImageContent = null
            };
            HabitationModel room = habitation.GetHabitationById(reservationModel.Habitation).GetAwaiter().GetResult();
            reservationModel.Habitation = room;
            ViewBag.Reservation = reservationModel;

            return View();
        }

        public ActionResult ReservationBill(ReservationModel reservationModel)
        {
            Habitation habitation = new Habitation();
            ReservationModel reservation = habitation.SetReservation(reservationModel).GetAwaiter().GetResult();
            ViewBag.Reservation = reservation;
            if (reservation.IdReservation != 0)
                this.sendEmail(reservation);
            return View();
        }

        public bool sendEmail(ReservationModel reservation)
        {
            try
            {
                string message = "¡Reservación realizada " + reservation.User.Name + "!" +
           "\nGracias, su reservación fue realizada exitosamente." +
            "\nNúmero de reservación: " + reservation.IdReservation + "" +
            "\nGracias por preferirnos!";

                SmtpMail objetoCorreo = new SmtpMail("TryIt");

                objetoCorreo.From = "pruebaing77@gmail.com";
                objetoCorreo.To = reservation.User.EmailAddress;
                objetoCorreo.Subject = "Reservación Natural Feelings Hotel";
                objetoCorreo.TextBody = message;

                SmtpServer objetoServidor = new SmtpServer("smtp.gmail.com");

                objetoServidor.User = "pruebaing77@gmail.com";
                objetoServidor.Password = "hktlmfllmyzpzwzh";
                objetoServidor.Port = 587;
                objetoServidor.ConnectType = SmtpConnectType.ConnectSSLAuto;

                SmtpClient objetoCliente = new SmtpClient();
                objetoCliente.SendMail(objetoServidor, objetoCorreo);
                return true;

            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

MVC/Natural Feelings Hotel/Natural Feelings Hotel/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;

namespace Natural_Feelings_Hotel.Controllers
{
    public class HotelController : Controller
    {

        private readonly IWebHostEnvironment webHostEnvironment;

        public HotelController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ComoLlegar()
        {
            return View();
        }

        public ActionResult ContacUs()
        {
            return View();
        }
    }
}

MVC/Natural Feelings Hotel/Natural Feelings Hotel/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
    Editorial by HTML5 UP
    html5up.net |
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
@using Microsoft.AspNetCore.Http
@using Natural_Feelings_Hotel.API
@{
    Advertising advertisingAPI = new Advertising();
    Offer offer = new Offer();

    //List<AdvertisingModel> adList = advertisingAPI.GetAds().GetAwaiter().GetResult();
    List<AdvertisingModel> advertisingModels = advertisingAPI.GetAds().GetAwaiter().GetResult();
    List<OfferModel> offersModels = offer.GetOffer().GetAwaiter().GetResult();
    Console.WriteLine(offersModels.Count());
}
<head>
    <title>Natural Feelings</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript">
        function changeImage1() {
            $('#probando').html('<img src="/galery/paseo.jpg" style="width:100%">');
        }
        function changeImage2() {
            $('#probando').html('<img src="/galery/paseo2.jpg" style="width:100%">');
        }
        function changeImage3() {
            $('#probando').html('<img src="/galery/rio.jpg" style="width:100%">');
        }
        function changeImage4() {
            $('#probando').html('<img src="/galery/bungee.jpg" style="width:100%">');
        }
        function changeImage5() {
            $('#probando').html('<img src="/galery/bungee2.jpg" style="width:100%">');
        }
        function changeImage6() {
            $('#probando').html('<img src="/galery/rafting.jpg" style="width:100%">');
        }
        function changeImage7() {
            $('#probando').html('<img src="/galery/termal.jpg" style="width:100%">');
        }
        function changeImage8() {
            $('#probando').html('<img src="/galery/termal2.jpg" style="width:100%">');
        }
    </script>
</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main">
            @RenderBody()

        </div>
        <!-- Sidebar -->
        <div id="sidebar">
            <div class="inner">
                <!-- Menu -->
                <nav id="menu">
                    <header class="major">
                        <h2>Menu</h2>
                    </header>
                    <ul>
                        <li><a asp-action="" asp-controller="">Inicio</a></li>
                        <li><a asp-controller="Hotel" asp-action="AboutUs">Sobre Nosotros</a></li>
                        <li><a asp-controller="Habitation" asp-action="Facilities">Facilidades</a></li>
                        <li><a asp-controller="Hotel" asp-action="ComoLlegar">¿Cómo llegar?</a></li>
                        <li><a asp-controller="Habitation" asp-action="Rate">Tarifas</a></li>
                        <li><a asp-controller="Habitation" asp-action="Reservation">Reservar en linea</a></li>
                        <li><a asp-controller="Hotel" asp-action="ContacUs">Contactenos</a></li>
                    </ul>
                </nav>

                <div>
                    <header class="major">
                        <h2>Publicidad</h2>
                    </header>
                    <div class="justify-content-center">
                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                @*
                                <div class="carousel-item active">
                                <a href="https://@adList[0].Link" target="_blank">
                                <img src="@adList[0].AdImage" style="width:100%" />
                                </a>
                                </div>
                                *@
                                @if (advertisingModels.Count != 0)
                                {
                                    <div class="carousel-item active">
                                        <a href="@advertisingModels[0].Link" target="_blank">
                                            <img src="~/AdvertisingImages/@advertisingModels[0].Image.IdImage@advertisingModels[0].Image.ImageFormat" style="width:100%" />
                                        </a>
                                    </div>

                                    @for (var i = 1; i < advertisingModels.Count; i++)
                                    {
                                        <div class="carousel-item">
                                            <a href="@advertisingModels[i].Link" target="_blank">
                                                <img src="~/AdvertisingImages/@advertisingModels[i].Image.IdImage@advertisingModels[i].Image.ImageFormat" style="width:100%" />
                                            </a>
                                        </div>
                                    }
                                    <!-- OfferList -->
                                    @for (var i = 0; i < offersModels.Count; i++)
                                    {
                                        <div class="carousel-item">
                                            <a href="/Offer/@offersModels[i].Id_Offer">
                                                @{
                                                    var base64 = Convert.ToBase64String(offersModels[i].Image.ImageContent);
                                                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                                                }
                                                <img src="@imgSrc" style="width: 100%;" />
                                            </a>
                                        </div>
                                    }
                                }
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>


                <!-- Footer -->
                <footer id="footer"
                    <p class="copyright">&copy; (2022) Hotel Natural Feelings.</p>
                </footer>

            </div>
        </div>

    </div>

    <!-- Scripts -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/browser.min.js"></script>
    <script src="~/js/breakpoints.min.js"></script>
    <script src="~/js/util.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>